apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-web-service
  labels:
    app: crud-web-service
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      env: crud
  template:
    metadata:
      labels:
        env: crud
    spec:
      containers:
      - name: web-service-app
        image: energy1971/crud_debug_service
        # edu_crud_service:latest
        env:
        # Define the environment variable
        - name: PG_HOST              # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: crud-cm             # The ConfigMap this value comes from.
              key: PG_HOST              # The key to fetch.
        - name: PG_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: crud-cm
              key: PG_DB_NAME
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: crud-secret
              key: PG_USER
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: crud-secret
              key: PG_PASSWORD
        ports:
        - name: web-port
          containerPort: 8000     
